# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Model(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, time=None):  # noqa: E501
        """Model - a model defined in OpenAPI

        :param name: The name of this Model.  # noqa: E501
        :type name: str
        :param time: The time of this Model.  # noqa: E501
        :type time: str
        """
        self.openapi_types = {
            'name': str,
            'time': str
        }

        self.attribute_map = {
            'name': 'name',
            'time': 'time'
        }

        self._name = name
        self._time = time

    @classmethod
    def from_dict(cls, dikt) -> 'Model':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Model of this Model.  # noqa: E501
        :rtype: Model
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Model.


        :return: The name of this Model.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Model.


        :param name: The name of this Model.
        :type name: str
        """

        self._name = name

    @property
    def time(self):
        """Gets the time of this Model.


        :return: The time of this Model.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this Model.


        :param time: The time of this Model.
        :type time: str
        """

        self._time = time
